import React from "react";

import { Segment, Card } from "semantic-ui-react";
import PlantCard from "./PlantCard";
import API from "./API";

const PLANTS = [
    {
      "id": 1,
      "created_at": "2019-02-28T17:10:53.482Z",
      "updated_at": "2019-02-28T17:10:53.482Z",
      "latin_name": "Adenocalymma comosum",
      "plant_habit": "Vine",
      "life_cycle": "Perennial",
      "sun_requirements": "Full Sun to Partial Shade",
      "water_preferences": "Mesic",
      "minimum_cold_hardiness": "Zone 10a -1.1 °C (30 °F) to +1.7 °C (35 °F)",
      "maximum_recommended_zone": null,
      "plant_height": null,
      "plant_spread": null,
      "leaves": "Evergreen",
      "flowers": "Showy",
      "bloom_size": "2\"-3\"",
      "underground_structures": "Taproot",
      "suitable_locations": "Houseplant. Espalier",
      "resistances": "Humidity tolerant",
      "propagation": "Other methods",
      "containers": "Needs excellent drainage in pots",
      "flower_color": "Yellow",
      "flower_time": "Late winter or early spring. Spring. Late spring or early summer. Summer",
      "wildlife_attractant": "Bees",
    //   "image_url": null,
      "soil_ph_preferences": null,
      "fruit": null,
    //   "commonname": null
    },
    {
      "id": 2,
      "created_at": "2019-02-28T17:11:15.214Z",
      "updated_at": "2019-02-28T17:11:15.214Z",
      "latin_name": "Aspidistra grandiflora",
      "plant_habit": "Herb/Forb",
      "life_cycle": "Perennial",
      "sun_requirements": "Partial or Dappled Shade. Partial Shade to Full Shade",
      "water_preferences": "Mesic",
      "minimum_cold_hardiness": "Zone 8b -9.4 °C (15 °F) to -6.7 °C (20 °F)",
      "maximum_recommended_zone": "Zone 11",
      "plant_height": "2 to 3 feet",
      "plant_spread": "2 to 3 feet",
      "leaves": "Evergreen. Broadleaf",
      "flowers": "Showy",
      "bloom_size": "4\"-5\"",
      "underground_structures": "Rhizome",
      "suitable_locations": "Xeriscapic. Houseplant",
      "resistances": "Drought tolerant",
      "propagation": "Other methods",
      "containers": "Suitable in 3 gallon or larger. Needs excellent drainage in pots",
      "flower_color": null,
      "flower_time": null,
      "wildlife_attractant": null,
      "image_url": null,
      "soil_ph_preferences": null,
      "fruit": null,
      "commonname": null
    },
    {
      "id": 3,
      "created_at": "2019-03-01T13:53:27.144Z",
      "updated_at": "2019-03-01T13:53:27.144Z",
      "latin_name": "Adiantum hispidulum 'Bronze Venus'",
      "plant_habit": "Fern",
      "life_cycle": "Perennial",
      "sun_requirements": "Partial or Dappled Shade",
      "water_preferences": "Mesic",
      "minimum_cold_hardiness": "Zone 8a -12.2 °C (10 °F) to -9.4 °C (15 °F)",
      "maximum_recommended_zone": "Zone 11",
      "plant_height": "12 to 18 inches",
      "plant_spread": "12 to 24 inches",
      "leaves": "Evergreen. Other",
      "flowers": null,
      "bloom_size": null,
      "underground_structures": "Rhizome",
      "suitable_locations": "Houseplant",
      "resistances": "Humidity tolerant",
      "propagation": "Other methods",
      "containers": "Needs excellent drainage in pots",
      "flower_color": null,
      "flower_time": null,
      "wildlife_attractant": null,
      "image_url": null,
      "soil_ph_preferences": null,
      "fruit": null,
      "commonname": null
    },
    {
      "id": 4,
      "created_at": "2019-03-01T13:57:37.634Z",
      "updated_at": "2019-03-01T13:57:37.634Z",
      "latin_name": "Adromischus cristatus 'Key Lime Pie'",
      "plant_habit": "Herb/Forb. Cactus/Succulent",
      "life_cycle": "Perennial",
      "sun_requirements": "Full Sun. Full Sun to Partial Shade",
      "water_preferences": null,
      "minimum_cold_hardiness": "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)",
      "maximum_recommended_zone": null,
      "plant_height": "4-8 inches",
      "plant_spread": null,
      "leaves": "Evergreen",
      "flowers": "Showy",
      "bloom_size": "Under 1\"",
      "underground_structures": null,
      "suitable_locations": "Xeriscapic. Houseplant",
      "resistances": "Humidity tolerant",
      "propagation": "Other methods",
      "containers": "Needs excellent drainage in pots",
      "flower_color": "White",
      "flower_time": "Late summer or early fall",
      "wildlife_attractant": null,
      "image_url": null,
      "soil_ph_preferences": null,
      "fruit": null,
      "commonname": null
    },
    {
      "id": 5,
      "created_at": "2019-03-01T13:59:38.174Z",
      "updated_at": "2019-03-01T13:59:38.174Z",
      "latin_name": "Aechmea orlandiana subsp. belloi",
      "plant_habit": null,
      "life_cycle": "Perennial",
      "sun_requirements": "Full Sun to Partial Shade",
      "water_preferences": "Mesic",
      "minimum_cold_hardiness": "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)",
      "maximum_recommended_zone": "Zone 11",
      "plant_height": null,
      "plant_spread": null,
      "leaves": "Evergreen",
      "flowers": "Showy",
      "bloom_size": null,
      "underground_structures": null,
      "suitable_locations": "Houseplant",
      "resistances": "Humidity tolerant",
      "propagation": "Other methods",
      "containers": "Needs excellent drainage in pots",
      "flower_color": null,
      "flower_time": null,
      "wildlife_attractant": null,
      "image_url": null,
      "soil_ph_preferences": null,
      "fruit": null,
      "commonname": null
    },
    {
      "id": 6,
      "created_at": "2019-03-01T14:04:55.602Z",
      "updated_at": "2019-03-01T14:04:55.602Z",
      "latin_name": "Aloe 'Pink Blush'",
      "plant_habit": "Cactus/Succulent",
      "life_cycle": "Perennial",
      "sun_requirements": "Full Sun",
      "water_preferences": "Dry Mesic. Dry",
      "minimum_cold_hardiness": null,
      "maximum_recommended_zone": null,
      "plant_height": "to 12 inches",
      "plant_spread": "8-12 inches",
      "leaves": "Evergreen. Variegated",
      "flowers": "Showy",
      "bloom_size": "Under 1\"",
      "underground_structures": null,
      "suitable_locations": "Xeriscapic. Houseplant",
      "resistances": null,
      "propagation": "Other methods",
      "containers": "Needs excellent drainage in pots",
      "flower_color": "Orange",
      "flower_time": "Late winter or early spring. Spring. Winter",
      "wildlife_attractant": "Hummingbirds",
      "image_url": null,
      "soil_ph_preferences": null,
      "fruit": "Dehiscent",
      "commonname": null
    },
    {
        "id": 1,
        "created_at": "2019-02-28T17:10:53.482Z",
        "updated_at": "2019-02-28T17:10:53.482Z",
        "latin_name": "Adenocalymma comosum",
        "plant_habit": "Vine",
        "life_cycle": "Perennial",
        "sun_requirements": "Full Sun to Partial Shade",
        "water_preferences": "Mesic",
        "minimum_cold_hardiness": "Zone 10a -1.1 °C (30 °F) to +1.7 °C (35 °F)",
        "maximum_recommended_zone": null,
        "plant_height": null,
        "plant_spread": null,
        "leaves": "Evergreen",
        "flowers": "Showy",
        "bloom_size": "2\"-3\"",
        "underground_structures": "Taproot",
        "suitable_locations": "Houseplant. Espalier",
        "resistances": "Humidity tolerant",
        "propagation": "Other methods",
        "containers": "Needs excellent drainage in pots",
        "flower_color": "Yellow",
        "flower_time": "Late winter or early spring. Spring. Late spring or early summer. Summer",
        "wildlife_attractant": "Bees",
      //   "image_url": null,
        "soil_ph_preferences": null,
        "fruit": null,
      //   "commonname": null
      },
      {
        "id": 2,
        "created_at": "2019-02-28T17:11:15.214Z",
        "updated_at": "2019-02-28T17:11:15.214Z",
        "latin_name": "Aspidistra grandiflora",
        "plant_habit": "Herb/Forb",
        "life_cycle": "Perennial",
        "sun_requirements": "Partial or Dappled Shade. Partial Shade to Full Shade",
        "water_preferences": "Mesic",
        "minimum_cold_hardiness": "Zone 8b -9.4 °C (15 °F) to -6.7 °C (20 °F)",
        "maximum_recommended_zone": "Zone 11",
        "plant_height": "2 to 3 feet",
        "plant_spread": "2 to 3 feet",
        "leaves": "Evergreen. Broadleaf",
        "flowers": "Showy",
        "bloom_size": "4\"-5\"",
        "underground_structures": "Rhizome",
        "suitable_locations": "Xeriscapic. Houseplant",
        "resistances": "Drought tolerant",
        "propagation": "Other methods",
        "containers": "Suitable in 3 gallon or larger. Needs excellent drainage in pots",
        "flower_color": null,
        "flower_time": null,
        "wildlife_attractant": null,
        "image_url": null,
        "soil_ph_preferences": null,
        "fruit": null,
        "commonname": null
      },
      {
        "id": 3,
        "created_at": "2019-03-01T13:53:27.144Z",
        "updated_at": "2019-03-01T13:53:27.144Z",
        "latin_name": "Adiantum hispidulum 'Bronze Venus'",
        "plant_habit": "Fern",
        "life_cycle": "Perennial",
        "sun_requirements": "Partial or Dappled Shade",
        "water_preferences": "Mesic",
        "minimum_cold_hardiness": "Zone 8a -12.2 °C (10 °F) to -9.4 °C (15 °F)",
        "maximum_recommended_zone": "Zone 11",
        "plant_height": "12 to 18 inches",
        "plant_spread": "12 to 24 inches",
        "leaves": "Evergreen. Other",
        "flowers": null,
        "bloom_size": null,
        "underground_structures": "Rhizome",
        "suitable_locations": "Houseplant",
        "resistances": "Humidity tolerant",
        "propagation": "Other methods",
        "containers": "Needs excellent drainage in pots",
        "flower_color": null,
        "flower_time": null,
        "wildlife_attractant": null,
        "image_url": null,
        "soil_ph_preferences": null,
        "fruit": null,
        "commonname": null
      },
      {
        "id": 4,
        "created_at": "2019-03-01T13:57:37.634Z",
        "updated_at": "2019-03-01T13:57:37.634Z",
        "latin_name": "Adromischus cristatus 'Key Lime Pie'",
        "plant_habit": "Herb/Forb. Cactus/Succulent",
        "life_cycle": "Perennial",
        "sun_requirements": "Full Sun. Full Sun to Partial Shade",
        "water_preferences": null,
        "minimum_cold_hardiness": "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)",
        "maximum_recommended_zone": null,
        "plant_height": "4-8 inches",
        "plant_spread": null,
        "leaves": "Evergreen",
        "flowers": "Showy",
        "bloom_size": "Under 1\"",
        "underground_structures": null,
        "suitable_locations": "Xeriscapic. Houseplant",
        "resistances": "Humidity tolerant",
        "propagation": "Other methods",
        "containers": "Needs excellent drainage in pots",
        "flower_color": "White",
        "flower_time": "Late summer or early fall",
        "wildlife_attractant": null,
        "image_url": null,
        "soil_ph_preferences": null,
        "fruit": null,
        "commonname": null
      },
      {
        "id": 5,
        "created_at": "2019-03-01T13:59:38.174Z",
        "updated_at": "2019-03-01T13:59:38.174Z",
        "latin_name": "Aechmea orlandiana subsp. belloi",
        "plant_habit": null,
        "life_cycle": "Perennial",
        "sun_requirements": "Full Sun to Partial Shade",
        "water_preferences": "Mesic",
        "minimum_cold_hardiness": "Zone 9b -3.9 °C (25 °F) to -1.1 °C (30 °F)",
        "maximum_recommended_zone": "Zone 11",
        "plant_height": null,
        "plant_spread": null,
        "leaves": "Evergreen",
        "flowers": "Showy",
        "bloom_size": null,
        "underground_structures": null,
        "suitable_locations": "Houseplant",
        "resistances": "Humidity tolerant",
        "propagation": "Other methods",
        "containers": "Needs excellent drainage in pots",
        "flower_color": null,
        "flower_time": null,
        "wildlife_attractant": null,
        "image_url": null,
        "soil_ph_preferences": null,
        "fruit": null,
        "commonname": null
      },
      {
        "id": 6,
        "created_at": "2019-03-01T14:04:55.602Z",
        "updated_at": "2019-03-01T14:04:55.602Z",
        "latin_name": "Aloe 'Pink Blush'",
        "plant_habit": "Cactus/Succulent",
        "life_cycle": "Perennial",
        "sun_requirements": "Full Sun",
        "water_preferences": "Dry Mesic. Dry",
        "minimum_cold_hardiness": null,
        "maximum_recommended_zone": null,
        "plant_height": "to 12 inches",
        "plant_spread": "8-12 inches",
        "leaves": "Evergreen. Variegated",
        "flowers": "Showy",
        "bloom_size": "Under 1\"",
        "underground_structures": null,
        "suitable_locations": "Xeriscapic. Houseplant",
        "resistances": null,
        "propagation": "Other methods",
        "containers": "Needs excellent drainage in pots",
        "flower_color": "Orange",
        "flower_time": "Late winter or early spring. Spring. Winter",
        "wildlife_attractant": "Hummingbirds",
        "image_url": null,
        "soil_ph_preferences": null,
        "fruit": "Dehiscent",
        "commonname": null
      }
  ]

export default class PlantsContainer extends React.Component {


    render() {
        const plants = this.props.plants.map(plant => < PlantCard key={plant.latin_name} plant={plant} />)
        
        return (
            <Segment.Group horizontal style={{overflow:'auto', whiteSpace:'nowrap', maxHeight:400}}>
                {plants}
            </Segment.Group>
        );
    }

    
};